# Change these first
owner: seamapi # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Seam API Overall Health
    url: https://connect.getseam.com/health
  - name: Brivo Login Working on Sandbox Workspaces
    url: https://connect.getseam.com/health/service/brivo.sandbox.login
  - name: Genie Login Working on Sandbox Workspaces
    url: https://connect.getseam.com/health/service/genie.sandbox.login
  - name: Akuvox Login Working on Sandbox Workspaces
    url: https://connect.getseam.com/health/service/akuvox.sandbox.login
  - name: August Login Working on Sandbox Workspaces
    url: https://connect.getseam.com/health/service/august.sandbox.login
  - name: Linear Login Working on Sandbox Workspaces
    url: https://connect.getseam.com/health/service/linear.sandbox.login
  - name: Schlage Login Working on Sandbox Workspaces
    url: https://connect.getseam.com/health/service/schlage.sandbox.login
  - name: Doorking Login Working on Sandbox Workspaces
    url: https://connect.getseam.com/health/service/doorking.sandbox.login
  - name: Genie Login Working on Production Workspaces
    url: https://connect.getseam.com/health/service/genie.production.login
  - name: August Login Working on Production Workspaces
    url: https://connect.getseam.com/health/service/august.production.login
  - name: Schlage Login Working on Production Workspaces
    url: https://connect.getseam.com/health/service/schlage.production.login
  - name: SmartThings Login Working on Sandbox Workspaces
    url: https://connect.getseam.com/health/service/smartthings.sandbox.login
  - name: Seam Relay Admin Login Working on Sandbox Workspaces
    url: https://connect.getseam.com/health/service/seam_relay_admin.sandbox.login

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
  
status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.seam.co
  # baseUrl: /
  logoUrl: https://www.seam.co/_next/image?url=%2Fimg%2Fseam-logos%2Fseam-wordmark-s.png&w=1920&q=75
  name: ""
  introTitle: "Seam Status"
  introMessage: Status of all Seam services. Integration downtime may sometimes be due to third party outage.
  navbar: []
